# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: skmtestorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-sls-skm
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-sls-skm

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 60

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
